name: Build Windows App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Clean React App
        env:
          CI: false
          GENERATE_SOURCEMAP: false
        # بناء الواجهة باستخدام React بدون Expo
        run: npm run build

      - name: Rename build folder to dist
        # تغيير اسم المجلد ليتوافق مع main.js
        run: Rename-Item -Path "build" -NewName "dist"

      - name: Build with Electron Builder
        run: npx electron-builder --win --publish never

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Executable-App
          path: release/*.exe
